### ISSUE TITLE
Traccar default port conflicts with MotionEye

### ISSUE THREAD

**Issue by SiliconAvatar** [hassio-addons/addon-traccar#1]
The way that MotionEye works is that the ports generated for each camera thread started at 8081 and go up, so thread-2 used 8082, thread-3 8083 and so on.

Traccar is set by default to use port 8082.

This means that when running both add-ons, if you have more than one camera in use with Motion Eye, the port conflict will kill the feeds for all cameras, generating the following Error in MotionEye:

>WARNING: mjpg client connection for camera 2 on port 8082 is closed

Because changing the default behaviour of MotionEye may be more difficult, I believe the prefered fix would be to use a different port (other than 8082) for Traccar.

**Comment by frenck** [comment]
The ports of Traccar are actually ALL customizable.

**Comment by SiliconAvatar** [comment]
> The ports of Traccar are actually ALL customizable.

Yes, I'm aware. And this port isnt even one of the traccar ports, 8082 is just the web UI port configurable right from the add-on config page in hass-io.

I just figured that since this port is not critical to anything about Traccar (only the UI) that it should probably be changed to something else to not conflict with an existing add-on.

**Comment by frenck** [comment]
That is actually a good idea and definitely something to look at before releasing it. 👍

**Comment by frenck** [comment]
Changed port to default 8072 to avoid conflicts.
