### ISSUE TITLE
Database persistance

### ISSUE THREAD

**Issue by jjanderson** [hassio-addons/addon-traccar#10]
# Problem/Motivation

1.  When you stop/start the addon, user database is purged and default restored with the only available user being admin / admin

2. It would appear that devices are also trashed on start/stop of add-on

## Expected behavior

The system configurations of users and devices (have not checked geofences, but assume that this is true here as well) shoudl be kept when starting/stopping the add-on

## Actual behavior

It would appear that database entries are not kept thought start/stop of add-on

## Steps to reproduce

1. Create a new user.
2. Disable admin account
3. Add device
4. Power off Add-on.
5. Reboot

## Proposed changes

?

**Comment by frenck** [comment]
With all the effort in the world, I'm absolutely not able to reproduce this.

**Comment by jjanderson** [comment]
Hi,

I managed to solve this by simply uninstalling and then re-installing. It seems to have solved my issue... THanks
