### ISSUE TITLE
Not updating to 0.2.0

### ISSUE THREAD

**Issue by HFsi** [hassio-addons/addon-traccar#11]
Hi!
I´m getting this error when I try to update 0.1.0 to 0.2.0:

19-02-27 15:59:38 INFO (SyncWorker_16) [hassio.docker.interface] Update Docker hassioaddons/traccar:v0.1.0 to hassioaddons/traccar:0.2.0
19-02-27 15:59:38 INFO (SyncWorker_16) [hassio.docker.interface] Pull image hassioaddons/traccar tag 0.2.0.
19-02-27 15:59:41 ERROR (SyncWorker_16) [hassio.docker.interface] Can't install hassioaddons/traccar:0.2.0 -> 500 Server Error: Internal Server Error ("readlink /mnt/data/docker/overlay2/l: invalid argument").

0.1.0 Works great

**Comment by frenck** [comment]
This is not an add-on issue, but an issue with Hass.io.

Please report it with them: home-assistant/hassio
