### ISSUE TITLE
Support Hass.io Ingress

### ISSUE THREAD

**Issue by mgriffin13** [hassio-addons/addon-traccar#12]
# Problem/Motivation

> Would like to use the Hass.io Ingress feature to automate web-ui access

## Expected behavior

> The Ingress feature to work

## Actual behavior

> Manual configuration

**Comment by fernandex00** [comment]
this could be done?

**Comment by frenck** [comment]
![image](https://user-images.githubusercontent.com/195327/59982336-cc230100-9610-11e9-921d-d13f9a94c822.png)

Yes, it can be done 😉

**Comment by fernandex00** [comment]
Awasome

**Comment by frenck** [comment]
Ingress support has been added to the dev branch and will be available on the next add-on update.
