### ISSUE TITLE
possible problem : trackar opening more than 180 ports

### ISSUE THREAD

**Issue by gnkarn** [hassio-addons/addon-traccar#13]
# Problem/Motivation
traccar interferes with appdaemon addon , even changing appdaemon to different ports couldnt make the hadasbopards to work , after testing different things it came out to be a conflict with both addons .
> (Why the issue was filed)
appdaemon and traccar not working properly together ( my case , of course not sure with others different configs)

## Expected behavior

> (What you expected to happen)

## Actual behavior
i see that traccar is opening more than 180 ports ( at least in the range i tested)
Open TCP Port: 	5001   		commplex-link
	 Open TCP Port: 	5002   		rfe
	 Open TCP Port: 	5003   		fmpro-internal
	 Open TCP Port: 	5004   		avt-profile-1
	 Open TCP Port: 	5005   		avt-profile-2
	 Open TCP Port: 	5006   		wsm-server
	 Open TCP Port: 	5007   		wsm-server-ssl
	 Open TCP Port: 	5008   		synapsis-edge
	 Open TCP Port: 	5009   		winfs
	 Open TCP Port: 	5010   		telelpathstart
	 Open TCP Port: 	5011   		telelpathattack
	 Open TCP Port: 	5012
	 Open TCP Port: 	5013
	 Open TCP Port: 	5014
	 Open TCP Port: 	5015
	 Open TCP Port: 	5016
	 Open TCP Port: 	5017
	 Open TCP Port: 	5018
	 Open TCP Port: 	5019
	 Open TCP Port: 	5020   		zenginkyo-1
	 Open TCP Port: 	5022   		mice
	 Open TCP Port: 	5023   		htuilsrv
	 Open TCP Port: 	5024   		scpi-telnet
	 Open TCP Port: 	5025   		scpi-raw
	 Open TCP Port: 	5026   		strexec-d
	 Open TCP Port: 	5027   		strexec-s
	 Open TCP Port: 	5028
	 Open TCP Port: 	5029
	 Open TCP Port: 	5030   		surfpass
	 Open TCP Port: 	5031
	 Open TCP Port: 	5032
	 Open TCP Port: 	5033
	 Open TCP Port: 	5034
	 Open TCP Port: 	5035
	 Open TCP Port: 	5036
	 Open TCP Port: 	5037
	 Open TCP Port: 	5039
	 Open TCP Port: 	5040
	 Open TCP Port: 	5041
	 Open TCP Port: 	5042   		asnaacceler8db
	 Open TCP Port: 	5043   		swxadmin
	 Open TCP Port: 	5044   		lxi-evntsvc
	 Open TCP Port: 	5045
	 Open TCP Port: 	5046
	 Open TCP Port: 	5047
	 Open TCP Port: 	5048
	 Open TCP Port: 	5049   		ivocalize
	 Open TCP Port: 	5050   		mmcc
	 Open TCP Port: 	5051   		ita-agent
	 Open TCP Port: 	5052   		ita-manager
	 Open TCP Port: 	5054
	 Open TCP Port: 	5055   		unot
	 Open TCP Port: 	5056   		intecom-ps1
	 Open TCP Port: 	5057   		intecom-ps2
	 Open TCP Port: 	5058
	 Open TCP Port: 	5059   		sds
	 Open TCP Port: 	5060   		sip
	 Open TCP Port: 	5061   		sip-tls
	 Open TCP Port: 	5062
	 Open TCP Port: 	5063
	 Open TCP Port: 	5064   		ca-1
	 Open TCP Port: 	5065   		ca-2
	 Open TCP Port: 	5066   		stanag-5066
	 Open TCP Port: 	5067   		authentx
	 Open TCP Port: 	5068
	 Open TCP Port: 	5069   		i-net-2000-npr
	 Open TCP Port: 	5070   		vtsas
	 Open TCP Port: 	5071   		powerschool
	 Open TCP Port: 	5072   		ayiya
	 Open TCP Port: 	5073   		tag-pm
	 Open TCP Port: 	5074   		alesquery
	 Open TCP Port: 	5075
	 Open TCP Port: 	5076
	 Open TCP Port: 	5077
	 Open TCP Port: 	5078
	 Open TCP Port: 	5079
	 Open TCP Port: 	5080
	 Open TCP Port: 	5081   		sdl-ets
	 Open TCP Port: 	5083
	 Open TCP Port: 	5085   		encrypted-llrp
	 Open TCP Port: 	5086
	 Open TCP Port: 	5087
	 Open TCP Port: 	5088
	 Open TCP Port: 	5089
	 Open TCP Port: 	5090
	 Open TCP Port: 	5091
	 Open TCP Port: 	5092
	 Open TCP Port: 	5093   		sentinel-lm
	 Open TCP Port: 	5094
	 Open TCP Port: 	5095
	 Open TCP Port: 	5096
	 Open TCP Port: 	5097
	 Open TCP Port: 	5098
	 Open TCP Port: 	5099   		sentlm-srv2srv
	 Open TCP Port: 	5100   		socalia
	 Open TCP Port: 	5101   		talarian-tcp
	 Open TCP Port: 	5102   		oms-nonsecure
	 Open TCP Port: 	5103
	 Open TCP Port: 	5105
	 Open TCP Port: 	5106
	 Open TCP Port: 	5107
	 Open TCP Port: 	5108
	 Open TCP Port: 	5109
	 Open TCP Port: 	5110
	 Open TCP Port: 	5111
	 Open TCP Port: 	5112   		pm-cmdsvr
	 Open TCP Port: 	5113
	 Open TCP Port: 	5114
	 Open TCP Port: 	5115
	 Open TCP Port: 	5116
	 Open TCP Port: 	5117
	 Open TCP Port: 	5118
	 Open TCP Port: 	5119
	 Open TCP Port: 	5120
	 Open TCP Port: 	5122
	 Open TCP Port: 	5123
	 Open TCP Port: 	5124
	 Open TCP Port: 	5126
	 Open TCP Port: 	5127
	 Open TCP Port: 	5128
	 Open TCP Port: 	5129
	 Open TCP Port: 	5130
	 Open TCP Port: 	5131
	 Open TCP Port: 	5132
	 Open TCP Port: 	5133   		nbt-pc
	 Open TCP Port: 	5134
	 Open TCP Port: 	5135
	 Open TCP Port: 	5136
	 Open TCP Port: 	5137   		ctsd
	 Open TCP Port: 	5139
	 Open TCP Port: 	5140
	 Open TCP Port: 	5141
	 Open TCP Port: 	5142
	 Open TCP Port: 	5143
	 Open TCP Port: 	5144
	 Open TCP Port: 	5145   		rmonitor_secure
	 Open TCP Port: 	5146
	 Open TCP Port: 	5147
	 Open TCP Port: 	5148
	 Open TCP Port: 	5149
	 Open TCP Port: 	5150   		atmp
	 Open TCP Port: 	5151   		esri_sde
	 Open TCP Port: 	5152   		sde-discovery
	 Open TCP Port: 	5153
	 Open TCP Port: 	5154   		bzflag
	 Open TCP Port: 	5155   		asctrl-agent
	 Open TCP Port: 	5156
	 Open TCP Port: 	5157
	 Open TCP Port: 	5159
	 Open TCP Port: 	5160
	 Open TCP Port: 	5161
	 Open TCP Port: 	5162
	 Open TCP Port: 	5163
	 Open TCP Port: 	5164
	 Open TCP Port: 	5165   		ife_icorp
	 Open TCP Port: 	5166   		winpcs
	 Open TCP Port: 	5167   		scte104
	 Open TCP Port: 	5168   		scte30
	 Open TCP Port: 	5169
	 Open TCP Port: 	5171
	 Open TCP Port: 	5172
	 Open TCP Port: 	5173
	 Open TCP Port: 	5174
	 Open TCP Port: 	5175
	 Open TCP Port: 	5176
	 Open TCP Port: 	5177
	 Open TCP Port: 	5178
	 Open TCP Port: 	5179
	 Open TCP Port: 	5180
	 Open TCP Port: 	5181

> (What actually happened)
by stopping traccar , appdaemon works , fine
even , when traccar web interface  is working , devices cant connect  .

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
The traccar configuration is available in your config directory: `/config/traccar.xml`, feel free to adjust it to your needs.

**Comment by sinclairpaul** [comment]
@gnkarn The port list used is available in this file https://github.com/hassio-addons/addon-traccar/blob/611c945eb7893c8a73fce4ff795404e1591d2aa3/traccar/rootfs/etc/traccar/hassio.xml#L75

The addon can do this as it is on the host network (and this is how the application works).  Within you config/traccar.xml you can add an entry for each like:

```<entry key='gps103.port'>0</entry>```

Which should make it pick a higher random port and may help with your issue.  Obviously you need to work out which device you are using so you do not change that one.
