### ISSUE TITLE
Report events using wrong query

### ISSUE THREAD

**Issue by zcsrf** [hassio-addons/addon-traccar#132]
# Problem/Motivation

Currently I am not able to show Events reports. I don't recall at what release I lost access. 
But even after a full home assistant fresh install, the problems persists.

## Expected behavior

When picking up the Report Type: Events, Configuring and pressing show, a list of events should be shown.

## Actual behavior

No list of events is reported and the website starts to misbehave (dialogs out of place)

Inspecting, we get the following responses form the server:

Headers: `Status 400 Bad Request`
Response: `Unknown column 'serverTime' in 'where clause' - SQLSyntaxErrorException (... < QueryBuilder:390 < DataManager:353 < Events:50 < ...)`

## Steps to reproduce

First and foremost, open the developer tools from your browser.
Request a report of the event type, and fill up the dialog with the required data.
Press to show

## Proposed changes

It seems, as far is I researched, that in the latest Traccar version, there where a change in the way the selectedEvents from the database are queried.

This happen in  the following [commit](https://github.com/traccar/traccar/commit/e28ae518fddc930dcb26d70a4456ee1b28fb0ecc#diff-df0ad6e43880f09c90ebf95f19110178aba6890df0010ebda7485029e2b543b4)

I believe it just a simple change in etc/traccar/hassio.xml file from:
`
   <entry key='database.selectEvents'>
        SELECT * FROM tc_events WHERE deviceId = :deviceId AND serverTime BETWEEN :from AND :to ORDER BY serverTime
    </entry>
`
to
`
    <entry key='database.selectEvents'>
        SELECT * FROM tc_events WHERE deviceId = :deviceId AND eventTime BETWEEN :from AND :to ORDER BY eventTime
    </entry>
`

Best Regards and keep up the amazing work.

**Comment by jonathanadams** [comment]
I have submitted a pull request #133 to fix this issue.

In the meantime you should be able to add the following to your `traccar.xml` located within the HA Config directory, the configuration in this file takes priority over anything in the `hassio.xml` file.

```xml
<entry key='database.selectEvents'>
    SELECT * FROM tc_events WHERE deviceId = :deviceId AND eventTime BETWEEN :from AND :to ORDER BY eventTime
</entry>
```

**Comment by zcsrf** [comment]
Hi @jonathanadams,

Indeed that fixes the issues.

Thanks for submitting the fix :+1:
