### ISSUE TITLE
Map drag on mobile phone

### ISSUE THREAD

**Issue by jorgebnunes** [hassio-addons/addon-traccar#157]
# Problem/Motivation
Finger map drag on on HA via ingress or mobile phone is not working

> (Why the issue was filed)
After last update

## Expected behavior
Map drag

## Steps to reproduce
open traccar plugin in HA or via Traccar Manager on mobile APP
The solution is to open list of available maps and close it, then map drag starts to work.
Map resize with two fingers work ok.
Thanks

**Comment by shirou93** [comment]
One tap on map and all touch function working correctly.
