### ISSUE TITLE
can't load traccar from add integrations menu

### ISSUE THREAD

**Issue by alexchini** [hassio-addons/addon-traccar#160]
When i try to load traccar from integration homeassistant menu i have always  an "Unknown error occurred message , in the log i find this error:

File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 116, in get_url
    raise NoURLAvailableError
homeassistant.helpers.network.NoURLAvailableError

**Comment by frenck** [comment]
This is the add-on, not an Home Assistant integration. Please report issues with integration with the Home Assistant project.

Thanks 👍
