### ISSUE TITLE
Only two ports opened

### ISSUE THREAD

**Issue by vgisbert** [hassio-addons/addon-traccar#175]
I have installed Traccar on my Home Assistant as an add-on from the Home Assistant Community Add-ons store with the intention of integrating a GPS tracker device (Sinotrack ST-901), and it does not work properly.
The type of installation is Home Assistant Supervised on Debian GNU/Linux 10 (buster) on a small PC (a kind of NUC).
In the router I have ports 5055 and 5013 mapped to the HA server.
I comment the tests that I have done:
1. I have installed a "Traccar Client" on the Android mobile and it works perfectly. It works through port 5055.
2. I have tried to use a public Traccar server (the demo3) and both the android client (port 5055) and the tracker device (port 5013) work perfectly.
3. The android client works perfectly.
4. I have done an nmap on my Home Assistant and only ports 5055 and 5037 are open.

Any idea why ports 5000-5150 are not open?

**Comment by vgisbert** [comment]
Yes, but I don't quite understand what I have to do.
This is that I have in /config/traccar.xml 

   -->

    

    <!-- // Example ports/protocols you can activate
    <entry key='gps103.port'>5001</entry>
    <entry key='tk103.port'>5002</entry>
    <entry key='gl100.port'>5003</entry>
    <entry key='gl200.port'>5004</entry>
    <entry key='t55.port'>5005</entry>
    <entry key='xexun.port'>5006</entry>
    <entry key='xexun.extended'>false</entry>
    <entry key='totem.port'>5007</entry>
    <entry key='enfora.port'>5008</entry>
    <entry key='meiligao.port'>5009</entry>
    <entry key='trv.port'>5010</entry>
    <entry key='suntech.port'>5011</entry>
    <entry key='progress.port'>5012</entry>
    <entry key='h02.port'>5013</entry>


And I want to enable this last protocol.
Would you be so kind to tell me what I have to put to enable it?

**Comment by frenck** [comment]
add it outside of the commented out block of XML configuration.

Before:

```xml
<!-- Enter you custom configuration below this line -->

<!-- // Example ports/protocols you can activate
<entry key='gps103.port'>5001</entry>
<entry key='tk103.port'>5002</entry>
<entry key='gl100.port'>5003</entry>
<entry key='gl200.port'>5004</entry>
<entry key='t55.port'>5005</entry>
<entry key='xexun.port'>5006</entry>
<entry key='xexun.extended'>false</entry>
<entry key='totem.port'>5007</entry>
<entry key='enfora.port'>5008</entry>
<entry key='meiligao.port'>5009</entry>
<entry key='trv.port'>5010</entry>
<entry key='suntech.port'>5011</entry>
<entry key='progress.port'>5012</entry>
<entry key='h02.port'>5013</entry>
...
-->
```

Before:

```xml
<!-- Enter you custom configuration below this line -->

<entry key='progress.port'>5012</entry>

<!-- // Example ports/protocols you can activate
<entry key='gps103.port'>5001</entry>
<entry key='tk103.port'>5002</entry>
<entry key='gl100.port'>5003</entry>
<entry key='gl200.port'>5004</entry>
<entry key='t55.port'>5005</entry>
<entry key='xexun.port'>5006</entry>
<entry key='xexun.extended'>false</entry>
<entry key='totem.port'>5007</entry>
<entry key='enfora.port'>5008</entry>
<entry key='meiligao.port'>5009</entry>
<entry key='trv.port'>5010</entry>
<entry key='suntech.port'>5011</entry>
<entry key='h02.port'>5013</entry>
...
-->
```

In case of progress is the one you want to enable. For more information about the Traccar configuration file, please consult the documentation of the Traccar project.

**Comment by frenck** [comment]
(sorry didn't mean to close it; just pressed the wrong button to reply)

**Comment by frenck** [comment]
No problem! ❤️
