### ISSUE TITLE
Latest version doesn't have "Show in sidebar" option

### ISSUE THREAD

**Issue by hoanglongutc** [hassio-addons/addon-traccar#185]
![image](https://user-images.githubusercontent.com/35026043/173225078-0960dd40-69a2-4334-be03-f726b687bf8f.png)

**Comment by donster22** [comment]
I have this problem today. what does "closed this as completed yesterday" mean please. Is there an update pending or did you fix it somehow? Thanks.

**Comment by frenck** [comment]
@donster22 Please make sure to actually read release notes. They are shown before upgrade, they can be viewed in the Home Assistant interface (before and after upgrade) and are listed here on the add-on repository:

<https://github.com/hassio-addons/addon-traccar/releases/tag/v0.17.0>

../Frenck

**Comment by donster22** [comment]
much appreciated and apologies. i completely missed this.

**Comment by hoanglongutc** [comment]
> much appreciated and apologies. i completely missed this.

have you fixed it yet?
