### ISSUE TITLE
 Reverse geocoding problem with opencagedata

### ISSUE THREAD

**Issue by DirkStorck** [hassio-addons/addon-traccar#187]
**Problem/Motivation**

getting an error when selecting "Show Address" within a tracked device plus on report generation the start and stop location are left blank within the interface and output the GPS coordinates when the report is exported
Expected behavior

Converts the gps coordinate to a reading address (https://www.traccar.org/reverse-geocoding/)
Actual behavior

Error Displayed on screen, "Reverse geocoding is not enabled - RuntimeException (Server Resource:69 < ...)"

**Steps to reproduce**
Click "Show Address" within the State section of a tracked device.
It can also be seen during report creation where the report does not show a start or end address.
Proposed changes

See link in Expected behaviour
Added these configuration parameters within the traccar.xml which was created under config after installing this add-on:

MY_KEY is the key I got from opencagedata

    <entry key='geocoder.enable'>true</entry>
    <entry key='geocoder.type'>opencagedata</entry>
    <entry key='geocoder.url'>http://api.opencagedata.com/geocode/v1</entry>
    <entry key='geocoder.key'>MY_KEY</entry>
    <entry key='geocoder.reuseDistance'>10</entry>
    <entry key='geocoder.format'>%f</entry>
    <entry key='geocoder.language'>de</entry> `

**Logs**
Don't know where I find these log containing the RuntimeException

**Comment by Justahobby01** [comment]
Have you tried restarting the add-on? After editing the traccar.xml and rebooting HA, I still needed to restart the add-on to get the geocoder to work.

**Comment by DirkStorck** [comment]
I had restarted Home Assistant several times...  will try to restart traccar addon.

**Comment by DirkStorck** [comment]
After restarting the add-on I don't get the error message anymore but if I now click on "show Address" nothing happens

**Comment by Justahobby01** [comment]
If you want to to try a different API,  Location IQ is working for me.

**Comment by DirkStorck** [comment]
Yes that is a great idea.  Could you share a configuration or where I can a "how to" ? Thank you!

**Comment by DirkStorck** [comment]
I have signed up and modified my traccar.xml with this 
`
<entry key='geocoder.enable'>true</entry>
<entry key='geocoder.type'>nominatim</entry>
<entry key='geocoder.url'>https://locationiq.org/v1/reverse.php</entry>
<entry key='geocoder.key'>your_key</entry>
`
your_key: is the token I have found in my profile of locationiq

The part using opencagedata I have removed

After reboot of home assistant and restart of the add-on I still don't get an error and NO address lookup if I click on "show Address"

**Comment by Justahobby01** [comment]
Below is the config I am  using:

`    <entry key='geocoder.onRequest'>false</entry>
    <entry key='geocoder.ignorePositions'>false</entry>
    <entry key='geocoder.enable'>true</entry>
    <entry key='geocoder.type'>nominatim</entry>
    <entry key='geocoder.url'>https://us1.locationiq.com/v1/reverse.php</entry>
    <entry key='geocoder.key'>API_KEY</entry>
`

**Comment by DirkStorck** [comment]
Thank you! that worked. I had to add 
`
<entry key='geocoder.onRequest'>false</entry> 
<entry key='geocoder.ignorePositions'>false</entry> 
`

But the main difference was the URL. I used "https://locationiq.org/v1/reverse.php" and "https://us1.locationiq.com/v1/reverse.php"
