### ISSUE TITLE
config addon to dedicated mysql

### ISSUE THREAD

**Issue by fedottt** [hassio-addons/addon-traccar#189]
Hi
how i can reconfigure addon for connect it to my dedicated mysql server?

**Comment by ShifuEst** [comment]
same question :)

**Comment by ShifuEst** [comment]
And error 
![Untitled](https://user-images.githubusercontent.com/67553888/188266220-24cd80a8-f798-440b-826b-a6eeca7fef43.jpg)

**Comment by tjorim** [comment]
The dedicated MySQL server would be the add-on, there will (probably) no support for external ones.

**Comment by ShifuEst** [comment]
Same error. i install mariadb in home assistant and still same error.

**Comment by tjorim** [comment]
> Same error. i install mariadb in home assistant and still same error. 

That error is unrelated to this request.
If you think it is a bug with the add-on: open a new issue.
However, in this case it looks more like you need some help with Traccar itself. Ask the question on Discord or use the Traccar help forum.

**Comment by fedottt** [comment]
Well, I setup traccar dedicated))
3 minutes and it work. Yes, I cant see it from hass, but now it work more quickly.
