### ISSUE TITLE
Update to v5.4? Addon stale?

### ISSUE THREAD

**Issue by smilebasti** [hassio-addons/addon-traccar#192]
Hi, is there an update coming to Traccar for Home Assistant as Traccar has already pushed v5.4?

Would be great to see the new Version.

Or can i help? Is there a guideline how to update an add-on?

**Comment by smilebasti** [comment]
Version 5.5 was released in the meantime. 

Any update on the horizon for this addon?

**Comment by ProtoxiDe22** [comment]
bump on this @frenck can give us any updates?
