### ISSUE TITLE
need update addon

### ISSUE THREAD

**Issue by pruwait** [hassio-addons/addon-traccar#195]
current version traccar is 5.5
pls update addon

**Comment by smilebasti** [comment]
See #192.
Sad to see this silent exit.

The newer versions added the possibility to export your track. Would have at least pushed #193.

Maybe frenck can give instructions on how to update manually to save your tracks.

**Comment by dadcoachengineer** [comment]
Would love to see this updated as well. 5.6 released this week.

Looks like it may be time to move this off of my HA node and onto a standalone container.

**Comment by konradwalsh** [comment]
Latest version supports events to MQTT

Would be nice!

**Comment by konradwalsh** [comment]
@ProtoxiDe22 
did your changes make it work with the new version?
I tried to manually make those changes but it fails to build
````
`The command '/bin/bash -o pipefail -c apk add --no-cache mariadb-client=10.6.10-r0 nginx=1.22.1-r0 nss=3.78.1-r0 openjdk11-jre-headless=11.0.17_p8-r1 xmlstarlet=1.6.1-r0 && curl -J -L -o /tmp/traccar.zip "https://github.com/traccar/traccar/releases/download/v5.0/traccar-other-5.0.zip" && mkdir -p /opt/traccar && unzip -d /opt/traccar /tmp/traccar.zip && rm -fr /tmp/*' returned a non-zero code: 2`
````

**Comment by ProtoxiDe22** [comment]
@konradwalsh it did work at the time i pushed it, the problem there is that the alpine package manager does not store old versions of the packages, so surely one of the packages was updated on the registry and the pinned version is not present anymore, you can probably solve by just unpinning the versions and let apk install the latest one

**Comment by konradwalsh** [comment]
> @konradwalsh it did work at the time i pushed it, the problem there is that the alpine package manager does not store old versions of the packages, so surely one of the packages was updated on the registry and the pinned version is not present anymore, you can probably solve by just unpinning the versions and let apk install the latest one

thanks for the quick reply..

I havem't a clue what you just said.... but here goes...!!

**Comment by ProtoxiDe22** [comment]
> > @konradwalsh it did work at the time i pushed it, the problem there is that the alpine package manager does not store old versions of the packages, so surely one of the packages was updated on the registry and the pinned version is not present anymore, you can probably solve by just unpinning the versions and let apk install the latest one
> 
> thanks for the quick reply..
> 
> I havem't a clue what you just said.... but here goes...!!

Change the Dockerfile to not have the packages version in the apk add command, like so 

`# Setup base
RUN \
    apk add --no-cache \
        mariadb-client \
        nginx \
        nss\
        openjdk11-jre-headless \`
        
        it should build fine after

**Comment by konradwalsh** [comment]
> > > @konradwalsh it did work at the time i pushed it, the problem there is that the alpine package manager does not store old versions of the packages, so surely one of the packages was updated on the registry and the pinned version is not present anymore, you can probably solve by just unpinning the versions and let apk install the latest one
> > 
> > 
> > thanks for the quick reply..
> > I havem't a clue what you just said.... but here goes...!!
> 
> Change the Dockerfile to not have the packages version in the apk add command, like so
> 
> ```
> RUN \
>     apk add --no-cache \
>         mariadb-client \
>         nginx \
>         nss \
>         openjdk11-jre-headless \ 
> ```
> 
> it should build fine after

thanks for being so help

It does build but fails to finish launching


anyway.. not your issue so I guess I will wait till it MIGHT be updated

**Comment by frenck** [comment]
Currently, development branch has been bumped and adjusted accordingly; now running Traccar 5.6.

Automatic updates have been put into place for the future as well.

../Frenck

**Comment by dadcoachengineer** [comment]
Thank you @frenck!
