### ISSUE TITLE
Possibility to use Nabucasa URL in the tracker

### ISSUE THREAD

**Issue by vitinhosessa** [hassio-addons/addon-traccar#197]
# Problem/Motivation

I have configured the traccar addon with the duckdns url. Now that I have decided to subscribe to HA Cloud with nabucasa, I would like to know if there is a possibility that I can configure my tracker with the nabucasa url.

My tracker uses port H2 5013

`<entry key='h02.port'>5013</entry>`

## Expected behavior

I would like to stop using duckdns and start using the nabucasa url

**Comment by vitinhosessa** [comment]
I found a tutorial in the HA community (https://community.home-assistant.io/t/traccar-via-nabu-casa-webhooks/130161) on how to make this connection with webhook. But I have a problem, the amount of characters generated in the webhook is too big (208 characters on average).

But my tracker has limitation of 152 characters for address. Can I decrease the number of characters in the url of the webhook?

**Comment by frenck** [comment]
This add-on doesn't support exposing it via the Nabu Casa URL.

../Frenck
