### ISSUE TITLE
Authentication problems in iframe

### ISSUE THREAD

**Issue by kseredynskyi** [hassio-addons/addon-traccar#198]
# Problem/Motivation

Can't use Traccar addon in iframe in HA companion application(separate tab with URL of Traccar) because since upgrade to version 0.17 it requires additional authentication (when enter credentials in that second login form the app crashes).

## Expected behavior

Ability to use plugin as a separate tab on HA dashboard.

## Actual behavior

After log in in iframe it asks for credentials for second time. After passing them second time the app crashes.

## Steps to reproduce

Add new tab to HA dashboard, enter Traccar URL to be shown on this tab, try to log in into Traccar using newly created tab.

## Proposed changes

Try to revert authentication-related changes in last update.

**Comment by frenck** [comment]
That is not an issue of the add-on, nor an issue the add-on can do anything about.

../Frenck
