### ISSUE TITLE
Uninstalling?

### ISSUE THREAD

**Issue by nicocoetzee** [hassio-addons/addon-traccar#199]
I removed the integration a few weeks ago. When I look at my MariaDB log I still see there multiple Traccar entries. I can exclude this in the conf.yaml, but I would prefer completely removing it. I looked for a folder in the file structure but saw nothing. See the screengrab below from the MariaDB logs.

Thank you in advance for any help.

![Screenshot 2023-03-21 at 09 46 53](https://user-images.githubusercontent.com/21128291/226682635-3b65fd6d-cbc4-42b9-abac-6f9d82453a81.png)

**Comment by sinclairpaul** [comment]
It won't remove the database when uninstalling the addon, you could use the phpmyadmin addon to drop the database if needed.

**Comment by nicocoetzee** [comment]
Great, thank you for the prompt response.
