### ISSUE TITLE
SSL properties also needed when not using ssl

### ISSUE THREAD

**Issue by WebSpider** [hassio-addons/addon-traccar#2]
When setting ssl to false, you still can't remove the certfile and keyfile config entries.

Doing so results in:

Not a valid value for dictionary value @ data['options']. Got {'log_level': 'info', 'port': 8072, 'ssl': False}

When adding cert/key statements back in, the addon starts successfully.

This is strange, since cert and key are only needed when doing ssl.

**Comment by tjorim** [comment]
Hi @You still need to leave the ssl-options in the config (`certfile`, `keyfile`) but the values are ignored as long as `ssl` is set to `false`.

**Comment by frenck** [comment]
@WebSpider Hass.io does not have conditional options. Hence, this is a limitation the add-on cannot work around.

Closing issue.
