### ISSUE TITLE
Geofence attribute of traccar device not updated after updating to v5.8

### ISSUE THREAD

**Issue by WouterKr** [hassio-addons/addon-traccar#241]
# Problem/Motivation

After upgrading to traccar addon v5.8 the geofence attribute of the Homeassistant traccar device is not updated anymore. 
Looking at the database of traccar the geofenceIds exits in the tc_positions table.
In Homeassistant the geofence attribute of a traccar device is/stays 'null'.

## Expected behavior

> source_type: gps
> latitude: xx.xxxxxx
> longitude: xx.xxxxxx
> gps_accuracy: 0
> battery: -1
> tracker: traccar
> address: ---------,---------
> speed: 0
> altitude: 11
> motion: false
> traccar_id: 2
> **geofence: value updated by the value of geofenceIds**
> category: car
> status: online
> ignition: false
> sat: 20
> friendly_name: car1
## Actual behavior

The state of a tracker entity does not have the value of the geofenceIds anymore. Instead is is 'null':

> source_type: gps
> latitude: xx.xxxxxx
> longitude: xx.xxxxxx
> gps_accuracy: 0
> battery: -1
> tracker: traccar
> address: ---------,---------
> speed: 0
> altitude: 11
> motion: false
> traccar_id: 2
> **geofence: null**
> category: car
> status: online
> ignition: false
> sat: 20
> friendly_name: car1

## Steps to reproduce

Update to v5.8

**Comment by frenck** [comment]
This is an add-on, not an integration. I think you have mixed those two up and ended up reporting the issue in an incorrect location.


../Frenck
