### ISSUE TITLE
Geofence attribute of traccar device not updated after updating to addon v0.20.0

### ISSUE THREAD

**Issue by WouterKr** [hassio-addons/addon-traccar#242]
# Problem/Motivation

Sorry about the first added issue with the same problem. This is about the add-on, not the integration.
 
After upgrading to traccar addon v0.20.0 the geofence attribute of the Homeassistant traccar device is not updated anymore.
Looking at the database of traccar the geofenceIds exits in the tc_positions table.
In Homeassistant the geofence attribute of a traccar device is/stays 'null'.

Configuration of devices and addon where not changed.

## Expected behavior

> source_type: gps
> latitude: xx.xxxxxx
> longitude: xx.xxxxxx
> gps_accuracy: 0
> battery: -1
> tracker: traccar
> address: ---------,---------
> speed: 0
> altitude: 11
> motion: false
> traccar_id: 2
> geofence: value updated by the value of geofenceIds
> category: car
> status: online
> ignition: false
> sat: 20
> friendly_name: car1

## Actual behavior

> source_type: gps
> latitude: xx.xxxxxx
> longitude: xx.xxxxxx
> gps_accuracy: 0
> battery: -1
> tracker: traccar
> address: ---------,---------
> speed: 0
> altitude: 11
> motion: false
> traccar_id: 2
> geofence: null
> category: car
> status: online
> ignition: false
> sat: 20
> friendly_name: car1
> 

## Steps to reproduce

Update to v0.20.0

**Comment by WouterKr** [comment]
The geofenceIds is getting updated on the traccar itself. The device state in homeassistant is not changed accordingly.
Do not know what has been changed in v0.20.0.

**Comment by WouterKr** [comment]
Updated to the latest version of the addon, version 0.21.0 did nog solve the issue.
GeofenceIds is not updated when it changes in traccar.

**Comment by mundeczek** [comment]
Issue still not fixed

**Comment by Hermit7777** [comment]
Updated to the latest version of the addon, version 0.22.0 did nog solve the issue.
GeofenceIds is not updated when it changes in traccar.

**Comment by WouterKr** [comment]
Version 0.22.0 did not solve the issue. Any change this will be solved in the next version?
