### ISSUE TITLE
Traccar devices not showing in HA

### ISSUE THREAD

**Issue by gysmo38** [hassio-addons/addon-traccar#25]
Traccar devices not apperat in HA with device_tracker

I've got Traccar  addon working well but when I add configuration in configuration.yml in HA nothing happen.

**Comment by gysmo38** [comment]
Here is a link with details [https://community.home-assistant.io/t/unable-to-get-traccar-device-tracker-in-ha/124424](https://community.home-assistant.io/t/unable-to-get-traccar-device-tracker-in-ha/124424)

**Comment by frenck** [comment]
This is out of scope for the add-on. The add-on does not provide the integration.

**Comment by gysmo38** [comment]
Ok but the addon should open the port 8072 and I do saw it open

**Comment by igorbljahhin** [comment]
> Ok but the addon should open the port 8072 and I do not saw it open

Do you have port mapping in addon configs, like on this screenshot?

![image](https://user-images.githubusercontent.com/1252230/63445040-643a3c80-c440-11e9-85a5-065ad07b3d66.png)

**Comment by frenck** [comment]
@gysmo38 That is not needed.

Use port `18682` and host `127.0.0.1`.

**Comment by gysmo38** [comment]
@frenck  Thanks a lot it work with port 18682 and host 127.0.0.1 :)
I will post on the other forum to let other known
