### ISSUE TITLE
SSH tunneling for tracker ports redirection stopped working

### ISSUE THREAD

**Issue by dtrochow** [hassio-addons/addon-traccar#268]
# Problem/Motivation

I am redirecting the ports from my public VPS machine to my local server, where Home Assistant is hosted.
It used to work and for some reason stopped working about 1 month ago. It could be caused by addon update or by Home Assistant Supervisor update.

## Expected behavior

I should be able to redirect the ports from my VPS to my local server using SSH tunneling. I have checked and the packets from my car GPS tracker are being received by VPS, but after setting up the SSH tunel, which redirects the ports to my local server they do not appear on my local server where traccar addon should receive them.

## Actual behavior

The packets are not being received on my local server side after setting up the SSH tunnel with port redirection.

## Steps to reproduce

N/A

This issue was confirmed by other person too. To reproduce it the setup with public VPS receiving car GPS tracker packets is needed.

## Proposed changes

Fix should make the SSH port redirection work again with traccar/Home Assistant.

**Comment by shirou93** [comment]
After update traccar.xml was moved to root dir and now addons like file editor not be able to open this file. Addons show only homeasssitant dir, not root dir. Traccar addon documentation not write about this breaking change, so maybe it's assotiated with this issue?
