### ISSUE TITLE
README assumes existing knowledge of Traccar project 

### ISSUE THREAD

**Issue by nickdos** [hassio-addons/addon-traccar#27]
# Problem/Motivation

Coming to this site with no idea what Traccar is, I could find no explanation for the name or where to find a list of compatible devices.

I finally googled "Traccar" and found the site https://www.traccar.org <== is this the source project? I have no idea but I'm guessing it is.

## Expected behavior

README should provide a link to https://www.traccar.org in the first few lines (assuming it is related to this add-on)

## Actual behavior

New user has no idea how to get started with a "tracker" nor has any idea what trackers are supported. I could not find a link to https://www.traccar.org anywhere on README.

**Comment by frenck** [comment]
Added in fbdbf59.
