### ISSUE TITLE
address,speed,motion and geofence attributes are not updated

### ISSUE THREAD

**Issue by gituletz** [hassio-addons/addon-traccar#280]
# Problem/Motivation
HomeAssistant device tracker received from Traccar is not updating the following attributes:  address,speed,motion,geofence

## Expected behavior
In Traccar the following attributes are updated: address,speed,motion,geofence, but in HomeAssistant device tracker is displaying them "null","0", "false"

## Actual behavior
source_type: gps
latitude: xxxx
longitude: xxx
gps_accuracy: 13.309000015258789
battery: 100
tracker: traccar
**address: null**
**speed: 0**
altitude: 121.1
**motion: false**
traccar_id: 2
**geofence: null**
category: person
status: online
friendly_name: xxxx

**Comment by frenck** [comment]
Hi there @gituletz 👋 

It seems like you are experiencing an issue with the Home Assistant Traccar integration, however, this is the issue tracker of the Home Assistant Traccar add-on. Add-ons and integrations are not the same thing.

Please report this issue with the Home Assistant project instead.

Thanks! 👍 

../Frenck
