### ISSUE TITLE
Traccar is using the internal H2 default database

### ISSUE THREAD

**Issue by tankdeer** [hassio-addons/addon-traccar#286]
I am receiving a warning on startup about using the internal H2 database. However I have MariaDB installed and running (and have for years)

```
[14:36:54] WARNING: Traccar is using the internal H2 default database!
[14:36:54] WARNING: THIS IS NOT RECOMMENDED!!!
[14:36:54] WARNING: Please install the official MariaDB add-on, to ensure
[14:36:54] WARNING: you are using a solid database for Traccar.
```

The documentation does not specify any additional configuration needed to use Maria instead of H2, so I am not sure why it's not using it. 

Is this a configuration issue, or is something else going on?

**Comment by sinclairpaul** [comment]
Try a full reboot, essentially the addon didn't detect the MariaDB addon is running (assuming you checked the logs there?), likely to be an issue on the Supervisor side.

**Comment by tankdeer** [comment]
That appeared to get it, thanks. I had checked the MariaDB logs previously, as well as restarting HA. A full reboot took care of, presumably because it restarts all the containers as well.
