### ISSUE TITLE
Port conflict

### ISSUE THREAD

**Issue by mcfrojd** [hassio-addons/addon-traccar#3]
# Problem/Motivation
I get this error in the log
`WARN: One of the protocols is disabled due to port conflict`
> (Why the issue was filed)

## Expected behavior
Dont know if or what it impacts, but i have an issue when i try to use the Google map (map sometimes dont show) using open street map works fine.
> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by deisi** [comment]
I have the same, but I guess I have another service running on the conflicting port. Traccar opens up a hell of a lot of ports. Thus conflict can easily happen basically everythin from 5000:5100 gets opened if I see it correctly.

**Comment by deisi** [comment]
and the addon runs in host mode. The result is, it just works, but on the oder hand, even though traccar support many many protocols, most people will just need one or two, so we should have a easy way of hardening the setup, by disabeling the undeeded protocols. Currently this can be done via the traccar.xml configuration file, but I think it would be nicer if we could do it via the addon config. Ideal would be something like:

`"enable_all_protocols": "true"`

that is true in the beginning and when it is turned off, one can specify a list of protocols to enable
`"enable_protocols": ("owntracks", "blabla", ...)` or maybe just a list of ports.

**Comment by frenck** [comment]
@deisi I like that idea, nevertheless, that would be a choice to either one of these:

- Open the full configuration for the user.
- Add-on managed configuration.

Currently, the add-on uses the first one (enabling all protocols as per default from Traccar).
I prefer the first one, to allow the user to configure everything about Traccar.
