### ISSUE TITLE
Traccar “monitored_conditions” not working

### ISSUE THREAD

**Issue by deanlongstaff** [hassio-addons/addon-traccar#32]
Hi,

I’m having some troubles getting monitored conditions pull in from traccar. I have it installed as a hassio add-on and use it to track my car.

I’m trying to get the satellite and total distance attributes, this is in my config:

`monitored_conditions: ['satellites', 'total distance']`

**Comment by frenck** [comment]
That is a question on the integration, not the add-on.
So please, file an issue on the Home Assistant repository, since the add-on has no control over the integration.
