### ISSUE TITLE
Traccar map images disappear

### ISSUE THREAD

**Issue by ebattulga** [hassio-addons/addon-traccar#38]
# Problem/Motivation
Access to image at 'https://maps.wikimedia.org/osm-intl/18/208898/91210.png' from origin 'https://MY SERVER URL' has been blocked by CORS policy: NO 'Access-Control-Allow-Origin' header is present on request resource. Error appear in Web inspector console window.

Relevant images attached in this post:
[this post](https://community.home-assistant.io/t/recent-update-block-traccar-map-images/170642)

**Comment by sinclairpaul** [comment]
If you expose the addon and access it, does the issue still occur?

**Comment by ebattulga** [comment]
@sinclairpaul how to expose my addon?

**Comment by pmitev** [comment]
I got this sorted by using Map layer: "Open Street Map"

**Comment by ebattulga** [comment]
> I got this sorted by using Map layer: "Open Street Map"

Thank you. It is working now. Maybe after update, selected map layer cleared.
