### ISSUE TITLE
Help me with the config of ``config/traccar.xml``

### ISSUE THREAD

**Issue by vitinhosessa** [hassio-addons/addon-traccar#39]
# Problem/Motivation

The new update ``v0.7.0`` requires that all protocols and ports, besides the web API, are now disabled by default! And you need to manually enable each protocol you need to use in the ``/config/traccar.xml`` file yourself.

I tried to read the traccar documentation. And i added this to the config file.

```
<entry key='[protocol].port'>5013</entry>
```

My GPS is a ``Sinotrack ST-901``, that uses ``H02`` protocol and the port is ``5013``.

## Expected behavior

My expected behavior was that everything was going to work. But probably i'm missing something.

## Actual behavior

The GPS doesn't connect to traccar.

## Steps to reproduce

Updating to ``v0.7.0`` and adding this:

```
<entry key='[protocol].port'>5013</entry>
```

to ``/config/traccar.xml``

## Full file - ``/config/traccar.xml``

```
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE properties SYSTEM 'http://java.sun.com/dtd/properties.dtd'>

<properties>

    <!--
    Loads default configuration for the Hass.io add-on.
    WARNING: Do not remove this line!
    -->
    <entry key='config.default'>/etc/traccar/hassio.xml</entry>

    <!--
    This is the main configuration file. All your configuration parameters should be placed in this file.
    Parameters in the main config file override values in the default file. Do not
    remove "config.default" parameter from this file unless you know what you are doing.
    For list of available parameters see following page:
        https://www.traccar.org/configuration-file/
    -->

    <!--
        Remove the comment from the block below to enable MySQL/MariaDB
        for Traccar. Don't forget to adjust it to your setup.
        (Usually, just setting the correct USERNAME & PASSWORD).
    -->
    <!-- // Remove this line to activate MySQL
    <entry key='database.driver'>com.mysql.jdbc.Driver</entry>
    <entry key='database.url'>jdbc:mysql://core-mariadb:3306/traccar?serverTimezone=UTC&amp;useSSL=false&amp;allowMultiQueries=true&amp;autoReconnect=true&amp;useUnicode=yes&amp;characterEncoding=UTF-8&amp;sessionVariables=sql_mode=''</entry>
    <entry key='database.user'>USERNAME</entry>
    <entry key='database.password'>PASSWORD</entry>
    // Remove this line to activate MySQL -->

    <!-- Enter you custom configuration below this line -->
    <entry key='[protocol].port'>5013</entry>

</properties>
```

**Comment by sinclairpaul** [comment]
The issue is the examples aren't added to existing config files.  You can see them at https://github.com/hassio-addons/addon-traccar/blob/master/traccar/rootfs/etc/traccar/traccar.xml

In your case it would likely be `<entry key='h02.port'>5013</entry>`

**Comment by vitinhosessa** [comment]
Thanks @sinclairpaul 🎉 

That worked. I knew i was missing something.
