### ISSUE TITLE
Loglevels not working

### ISSUE THREAD

**Issue by deisi** [hassio-addons/addon-traccar#4]
# Problem/Motivation
loglevels dont seem to work. I tested `warning` and `error`, both gave `info` level error messages
> (Why the issue was filed)

## Expected behavior
should change the log level
> (What you expected to happen)

## Actual behavior
does nothing
> (What actually happened)

## Steps to reproduce
change loglevel in traccar addon config to `warning`
> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Could you be a little more specific?
Please provide logs and configs.

**Comment by deisi** [comment]
Okay, I close this now, It started to work. Dunno what went wrong
