### ISSUE TITLE
Traccar config traccar.xml not working after update 0.7.1

### ISSUE THREAD

**Issue by shirou93** [hassio-addons/addon-traccar#40]
# Problem/Motivation

Traccar create empty database after start

## Expected behavior

Connect to external mysql. 

## Steps to reproduce

Before i config datebase in traccar.xml file

## Proposed changes

add possible to change config in traccar.xml. Before update it was possible.

**Comment by sinclairpaul** [comment]
Can you give a few more details on your setup?

Do you have the MariaDB addon installed?  I can see a possible issue where the MariaDB addon is running and you wish to use an external DB on a separate host, is this your use case?

**Comment by shirou93** [comment]
I have MariaDB addon only for HA db.  I create traccar.xml in HA directory and conncet to external mysql server (another pc) via https://www.traccar.org/mysql/. After update traccar ignore my config to connect db in traccar.xml file and create empty db in mariadb addon.

**Comment by frenck** [comment]
Please create a separate issue for different things (don't stack, it makes tracking impossible).

For the database, yeah, that is an oversight, will fix that.

**Comment by frenck** [comment]
Addressed in v0.7.2
