### ISSUE TITLE
Email notification native not working ver 0.7.1

### ISSUE THREAD

**Issue by shirou93** [hassio-addons/addon-traccar#41]
# Problem/Motivation

email native notfication from traccar not working

## Expected behavior

email should working native when will config in traccar.xml file

## Actual behavior

New version addon traccar have error when i trying send test notification. (Older version addon working well)

## Steps to reproduce
Config like this (gmail): https://www.traccar.org/documentation/notifications/ 
![obraz](https://user-images.githubusercontent.com/59237288/75628468-84aa3700-5bd9-11ea-9a05-ed05123f1d30.png)

<blockquote><div><strong><a href="https://www.traccar.org/documentation/notifications/">Notifications - Documentation - Traccar</a></strong></div></blockquote>

**Comment by sinclairpaul** [comment]
Not sure why the SMTP server would return an HTTP response, are you 100% sure you configuration is correct?

**Comment by shirou93** [comment]
This config from documentation traccar.
This config was working on older version addon.
I don't change anything, only update addon on HA.

**Comment by sinclairpaul** [comment]
The add on itself won't have changed anything related to this that I can see (as it appears to just be an outgoing SMTP connection).  As it wraps the existing software, I would suggest asking at the traccar repo itself.

**Comment by shirou93** [comment]
traccar logs when i trying send test messages:

> 172.30.32.1(172.30.32.2) POST /api/notifications/test HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firefox/73.0)

> 172.30.32.1(172.30.32.2) GET /api/socket HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firefox/73.0)

I thing this is addon issue. No issues witch email on official traccar github.

**Comment by sinclairpaul** [comment]
Can you expose the addon and restest (i.e. set a network port and access using that)

**Comment by shirou93** [comment]
expose working.

**Comment by sinclairpaul** [comment]
Then the issue was likely introduced in v0.5.0, I would suggest it could be that it is just the test functionality that is broken, however will look at it when possible.

**Comment by shirou93** [comment]
Thanks
