### ISSUE TITLE
Running in host networking mode

### ISSUE THREAD

**Issue by intlabs** [hassio-addons/addon-traccar#42]
# Problem/Motivation

This addon runs in host networking mode, as the node I run hassio on has a more restrictive firewall than is typical for hassio deployments I got a 502 in the Lovelace UI via ingress.

## Expected behavior

A default installation to work without needing modification.

## Actual behavior

Could not access the web interface via Home Assistants front end, additionally as the container is running in the hosts networking namespace when selecting a port to bind to if bypassing ingress there is no feedback via the dockerapi etc.

## Steps to reproduce

Run-on a machine with a reasonable firewall in place (in this case firewalld with debian's default zone config). Its rather hard to work around this with a static rule I think, as the port assigned by ha is dynamic?

## Proposed changes

If possible, could we change this to false? https://github.com/hassio-addons/addon-traccar/blob/fd912a9d4dfbd007533a4b30c7700e272e3b0079/traccar/config.json#L17

**Comment by frenck** [comment]
No we can't as we can't predict the ports used.
