### ISSUE TITLE
Traccar Manager Access - Direct WebUI access

### ISSUE THREAD

**Issue by Benouzao** [hassio-addons/addon-traccar#43]
Hello,
Is it possible to access the traccar addon using Traccar Manager or direct URL access. I was trying to find which port it is running on by default and if I can change it. 
Tried <entry key='web.port'>8082</entry> in traccar.xml but that didn't help.
I know this may sound counter intuitive as I can access the same via HA WebUI, but I have a slow connection on my phone and accessing via Traccar Manager may be lighter.
Thanks a lot,
Ben

**Comment by sinclairpaul** [comment]
On the Network tab assign a port to the web ui and restart the addon.

**Comment by shirou93** [comment]
> Hello,
> Is it possible to access the traccar addon using Traccar Manager or direct URL access. I was trying to find which port it is running on by default and if I can change it.
> Tried 8082 in traccar.xml but that didn't help.
> I know this may sound counter intuitive as I can access the same via HA WebUI, but I have a slow connection on my phone and accessing via Traccar Manager may be lighter.
> Thanks a lot,
> Ben

You can add port in super visor on config addon.

![image](https://user-images.githubusercontent.com/59237288/86883703-b20c7180-c0f2-11ea-8a30-2d981f23038b.png)

**Comment by Benouzao** [comment]
Thanks a lot @shirou93
