### ISSUE TITLE
Timeouterror connecting to Traccar,

### ISSUE THREAD

**Issue by RenzoBeux** [hassio-addons/addon-traccar#44]
# Problem/Motivation

Warning spam in the log, so annoying

## Expected behavior

Not to make warnings

## Actual behavior
¨Details¨ (it is in spanish that why the quotes) (WARNING)
Logger: pytraccar.api
Source: __main__.py:356
Timeouterror connecting to Traccar,

## Steps to reproduce

I dont know, i just installed traccar and setup 2 mobile clients.

## Proposed changes

Maybe increase timeout? I mean i dont know what timeout is at least it seems none of the configurables cause i tried changing them all

**Comment by RenzoBeux** [comment]
If you want, i cant write down debug info, but it is all normal with the right location and user info. If you want it anyway i will be glad to post it.

**Comment by frenck** [comment]
The error you show is from the Home Assistant integration, this is the add-on repository. While the integration can be used to connect to the add-on, it isn't related. Please report your issue with Home Assistant. Thanks 👍
