### ISSUE TITLE
Multiple DatabaseException on a fresh install

### ISSUE THREAD

**Issue by zcsrf** [hassio-addons/addon-traccar#45]
# Problem/Motivation

Multiple database issues after fresh install
After a clean install should the basics work

## Expected behavior

Traccar reaching the nginx and starting.

## Actual behavior

Multiple liquibase.exception.DatabaseException: Table 'tc_attributes' already exists.
Constantly re-starting.

## Steps to reproduce

After fresh install, start the add-on

### Extra Info

I have the MariaDB addon Current version: 2.1.2
Also uninstalled the traccar addon (and deleted the config/traccar.xml) and installed again. 
Same issue

### Log

> [19:09:07] INFO: Starting Traccar server...
> Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
> 2020-06-30 19:09:08  INFO: HikariPool-1 - Starting...
> 2020-06-30 19:09:08  WARN: Registered driver with driverClassName=com.mysql.jdbc.Driver was not found, trying direct instantiation.
> 2020-06-30 19:09:08  INFO: HikariPool-1 - Start completed.
> 2020-06-30 19:09:09  INFO: Clearing database change log checksums
> 2020-06-30 19:09:09  INFO: SELECT COUNT(*) FROM traccar.DATABASECHANGELOGLOCK
> 2020-06-30 19:09:09  INFO: SELECT COUNT(*) FROM traccar.DATABASECHANGELOGLOCK
> 2020-06-30 19:09:09  INFO: SELECT `LOCKED` FROM traccar.DATABASECHANGELOGLOCK WHERE ID=1
> 2020-06-30 19:09:09  INFO: Successfully acquired change log lock
> 2020-06-30 19:09:09  INFO: SELECT MD5SUM FROM traccar.DATABASECHANGELOG WHERE MD5SUM IS NOT NULL LIMIT 1
> 2020-06-30 19:09:09  INFO: UPDATE traccar.DATABASECHANGELOG SET MD5SUM = NULL
> 2020-06-30 19:09:09  INFO: Successfully released change log lock
> 2020-06-30 19:09:09  INFO: SELECT COUNT(*) FROM traccar.DATABASECHANGELOGLOCK
> 2020-06-30 19:09:09  INFO: SELECT COUNT(*) FROM traccar.DATABASECHANGELOGLOCK
> 2020-06-30 19:09:09  INFO: SELECT `LOCKED` FROM traccar.DATABASECHANGELOGLOCK WHERE ID=1
> 2020-06-30 19:09:09  INFO: Successfully acquired change log lock
> 2020-06-30 19:09:09  INFO: Can not use class liquibase.parser.core.json.JsonChangeLogParser as a Liquibase service because org.yaml.snakeyaml.constructor.BaseConstructor is not in the classpath
> 2020-06-30 19:09:09  INFO: Can not use class liquibase.parser.core.yaml.YamlChangeLogParser as a Liquibase service because org.yaml.snakeyaml.constructor.BaseConstructor is not in the classpath
> 2020-06-30 19:09:10  INFO: SELECT MD5SUM FROM traccar.DATABASECHANGELOG WHERE MD5SUM IS NOT NULL LIMIT 1
> 2020-06-30 19:09:10  INFO: SELECT COUNT(*) FROM traccar.DATABASECHANGELOG
> 2020-06-30 19:09:10  INFO: Reading from traccar.DATABASECHANGELOG
> 2020-06-30 19:09:10  INFO: SELECT * FROM traccar.DATABASECHANGELOG ORDER BY DATEEXECUTED ASC, ORDEREXECUTED ASC
> 2020-06-30 19:09:11  INFO: CREATE TABLE traccar.tc_attributes (id INT AUTO_INCREMENT NOT NULL, `description` VARCHAR(4000) NOT NULL, type VARCHAR(128) NOT NULL, attribute VARCHAR(128) NOT NULL, expression VARCHAR(4000) NOT NULL, CONSTRAINT PK_TC_ATTRIBUTES PRIMARY KEY (id))
> 2020-06-30 19:09:11 ERROR: Change Set changelog-4.0-clean::changelog-4.0-clean::author failed.  Error: Table 'tc_attributes' already exists [Failed SQL: (1050) CREATE TABLE traccar.tc_attributes (id INT AUTO_INCREMENT NOT NULL, `description` VARCHAR(4000) NOT NULL, type VARCHAR(128) NOT NULL, attribute VARCHAR(128) NOT NULL, expression VARCHAR(4000) NOT NULL, CONSTRAINT PK_TC_ATTRIBUTES PRIMARY KEY (id))]
> 2020-06-30 19:09:11  INFO: Successfully released change log lock
> 2020-06-30 19:09:11 ERROR: Main method error - Table 'tc_attributes' already exists - SQLSyntaxErrorException (... < DataManager:312 < *:90 < Context:292 < Main:110 < ...)
> Exception in thread "main" java.lang.RuntimeException: liquibase.exception.MigrationFailedException: Migration failed for change set changelog-4.0-clean::changelog-4.0-clean::author:
>      Reason: liquibase.exception.DatabaseException: Table 'tc_attributes' already exists [Failed SQL: (1050) CREATE TABLE traccar.tc_attributes (id INT AUTO_INCREMENT NOT NULL, `description` VARCHAR(4000) NOT NULL, type VARCHAR(128) NOT NULL, attribute VARCHAR(128) NOT NULL, expression VARCHAR(4000) NOT NULL, CONSTRAINT PK_TC_ATTRIBUTES PRIMARY KEY (id))]
> 	at org.traccar.Main.run(Main.java:152)
> 	at org.traccar.Main.main(Main.java:104)
> Caused by: liquibase.exception.MigrationFailedException: Migration failed for change set changelog-4.0-clean::changelog-4.0-clean::author:
>      Reason: liquibase.exception.DatabaseException: Table 'tc_attributes' already exists [Failed SQL: (1050) CREATE TABLE traccar.tc_attributes (id INT AUTO_INCREMENT NOT NULL, `description` VARCHAR(4000) NOT NULL, type VARCHAR(128) NOT NULL, attribute VARCHAR(128) NOT NULL, expression VARCHAR(4000) NOT NULL, CONSTRAINT PK_TC_ATTRIBUTES PRIMARY KEY (id))]
> 	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:646)
> 	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:53)
> 	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:83)
> 	at liquibase.Liquibase.update(Liquibase.java:202)
> 	at liquibase.Liquibase.update(Liquibase.java:179)
> 	at liquibase.Liquibase.update(Liquibase.java:175)
> 	at org.traccar.database.DataManager.initDatabaseSchema(DataManager.java:312)
> 	at org.traccar.database.DataManager.<init>(DataManager.java:90)
> 	at org.traccar.Context.init(Context.java:292)
> 	at org.traccar.Main.run(Main.java:110)
> 	... 1 more
> Caused by: liquibase.exception.DatabaseException: Table 'tc_attributes' already exists [Failed SQL: (1050) CREATE TABLE traccar.tc_attributes (id INT AUTO_INCREMENT NOT NULL, `description` VARCHAR(4000) NOT NULL, type VARCHAR(128) NOT NULL, attribute VARCHAR(128) NOT NULL, expression VARCHAR(4000) NOT NULL, CONSTRAINT PK_TC_ATTRIBUTES PRIMARY KEY (id))]
> 	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:402)
> 	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:59)
> 	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:131)
> 	at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1276)
> 	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1258)
> 	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:609)
> 	... 10 more
> Caused by: java.sql.SQLSyntaxErrorException: Table 'tc_attributes' already exists
> 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
> 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
> 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
> 	at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:764)
> 	at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:648)
> 	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:398)
> 	... 15 more
> [19:09:11] INFO: Starting Traccar server...

If anyone can help me fix this. I would appreciate.
Thanks

**Comment by sinclairpaul** [comment]
Not sure its a fresh install as the Database looks to already exist.  I would suggest you delete the DB (PHPMyadmin addon can help you there if you need), and restart.

**Comment by zcsrf** [comment]
Hi @sinclairpaul ,

Maybe that was the issue. On my first try it took a lot of time and I must have stopped the process to add the log level.
Seems that deleting the database and waiting a bit of time worked.

Thanks for the help.
Will close the issue
