### ISSUE TITLE
[0.8.0] Switch to modern interface on login page got error 404

### ISSUE THREAD

**Issue by shirou93** [hassio-addons/addon-traccar#46]
# Problem/Motivation
Switch to modern interface on login page got error 404

## Expected behavior
Turn on modern interface

## Actual behavior
Error 404

## Steps to reproduce
Click "switch to modern interface" on login page.

**Comment by frenck** [comment]
Interesting probably needs additional rules for handling that using Ingress.

**Comment by nightscoutteun** [comment]
Is there already a update on this?

**Comment by frenck** [comment]
nope, feel free to contribute a fix for it.

**Comment by abrileroux** [comment]
Still doesn't work on the latest version unfortunately.

**Comment by asiersan** [comment]
Still not runing
