### ISSUE TITLE
<entry key='h02.port'>5013</entry>

### ISSUE THREAD

**Issue by JochenKlenk** [hassio-addons/addon-traccar#49]
# Problem/Motivation

after add line "<entry key='h02.port'>5013</entry>" in traccar.xml  the port is still not open.

addon restarted / hass restarted / port checked over docker and netstat

Can you help?

Thanks

**Comment by sinclairpaul** [comment]
Please share the traccar.xml with changes.

**Comment by JochenKlenk** [comment]
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE properties SYSTEM 'http://java.sun.com/dtd/properties.dtd'>

<properties>

    
    <entry key='config.default'>/etc/traccar/hassio.xml</entry>

    

    
    <entry key='h02.port'>5013</entry>
    

</properties>

**Comment by sinclairpaul** [comment]
The config is fine and works:

![image](https://user-images.githubusercontent.com/24625998/98542271-a4145c00-225e-11eb-8fa1-04424690e5bb.png)

Please consider the container runs on the host network, why do you believe the port is closed?  What netstat command are you running on the host?

**Comment by frenck** [comment]
no response.
