### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by fuzunspm** [hassio-addons/addon-traccar#5]
# Problem/Motivation
I’m getting bad gateway when tryin to access web ui, no error log and I tried different ports but no luck

**Comment by frenck** [comment]
- Have you checked the logs?
- Please provide logs. There is nothing for me to do with this one sentence.

**Comment by fuzunspm** [comment]
All it says is:

2019-01-01 22:04:50  INFO: HikariPool-1 - Starting...
2019-01-01 22:04:52  INFO: HikariPool-1 - Start completed.
2019-01-01 22:05:08  INFO: Clearing database change log checksums
2019-01-01 22:05:09  INFO: SELECT COUNT(*) FROM PUBLIC.DATABASECHANGELOGLOCK
2019-01-01 22:05:09  INFO: SELECT COUNT(*) FROM PUBLIC.DATABASECHANGELOGLOCK
2019-01-01 22:05:09  INFO: SELECT LOCKED FROM PUBLIC.DATABASECHANGELOGLOCK WHERE ID=1
2019-01-01 22:05:10  INFO: Waiting for changelog lock....

**Comment by hubgitbb** [comment]
same proble here with the same logs
i am runing Home Assistant 0.84.6

**Comment by Aterfax** [comment]
Also can confirm this error.

**Comment by Aterfax** [comment]
Also can confirm this error.

`ERROR: Main method error - Could not acquire change log lock.  Currently locked by homeassistant (172.30.32.1) since 1/8/19 3:01 AM - LockException (... < DataManager:310 < *:90 < Context:382 < Main:110 < ...)
Exception in thread "main" java.lang.RuntimeException: liquibase.exception.LockException: Could not acquire change log lock.  Currently locked by homeassistant (172.30.32.1) since 1/8/19 3:01 AM`

I am fairly sure now that this error is related to the addon getting restarted before the install has completed leading to the database being stuck in a locked state.

To resolve this error, simply uninstall and re-install giving it plenty of time even when it is giving a 502 error to finish completing the install.

This may be a significant amount of time on slow devices.

**Comment by hubgitbb** [comment]
re-installing worked for me. thx

**Comment by cybergrimes** [comment]
I reinstalled/restarted HA but thought I was still getting the error but it looks like it just took a while for it to start the service. It's running now.

**Comment by bandric1** [comment]
That issue i experienced while i was on RPI3B+ MariaDB would lock a table and would not unlock it even if request was issued. After i moved to Laptop i havent experienced that issue any more.
This is somehow R/W bug in MariaDB it locks. I found the sollution of using remote MariaDB to which i could connect with remote tool (sequel pro) if that happened i could easily unlock the database table and continue.

**Comment by HFsi** [comment]
Same on 0.91.3.....no error logs.
The update from 0.1.0 didn't work for me, so I uninstalled it and installed 0.3.0 from scratch

**Comment by Aterfax** [comment]
I have had this happen too often and the quickest way to resolve it is just deleting the DB. This does lose the data so it might be a better solution that the docker start script has a section written in to force an unlock of the tables prior to Traccar start up.

This shouldn't cause issues as the file locking can't possibly actually be occurring since the docker just restarted but I do not know the commands to achieve this.

**Comment by myopenflixr** [comment]
I am experiencing this issue as well. I originally uninstalled and deleted the database....reinstalled....and it worked fine.

However, when I just performed a reboot of my RPi3-B+, I now have the same issue.

This needs to be resolved. I would rather not have to uninstall....delete database....and then reinstall every time I need to reboot my RPi.

**Comment by Aterfax** [comment]
Agreed - @frenck any chance you could add a force unlock to the database as part of the docker start scripting?

**Comment by Aterfax** [comment]
SSH into the host and either get a terminal inside the the docker or go to the config folders inside of hassio / the docker and delete the db file.Should be under /config inside the docker or somewhere in /usr/share/hassio/ on the host.File paths should be relatively easy to find for either but I am on mobile and can't recall the exact file paths from memory. Google will help if you can't find the right place straight away.

**Comment by BatterBits** [comment]
I'm having the same problem. I'm more than happy to get my "hands dirty" - if I only knew where/how to start.
I'm using Hssio - and can't find how to "get into" the docker - and there's nothing which looks right under /usr/share - there's no usr/share/hassio on my device.

**Comment by Aterfax** [comment]
Then the folder structure depends on how you've installed Hassio I suspect.

Using the "where" command on the hassio executables might help?

**Comment by BatterBits** [comment]
Okay - so to update my previous - it seems I was using a protected mode (from within Hassio - IDE) so wasn't able to see the docker processes.

Here's how to do it.
Access your Hassio via SSH - I wasn't able to get Hassio tools IDE to work, but managed inHassio add-on  SSH&Web Terminal, but I had to turn "protected mode" off - toggle switch in top panel.

Run command 
`docker ps |grep traccar`
this will produce a listing where the first column has a number in Hex - this is the ID of the container. 
Then run

`docker exec <your ID from previous step> ls -ltr /data`

This should list 2 databases which can be removed as follows:
`docker exec <your ID > rm /data/traccar.trace.db`
`docker exec <your ID > rm /data/traccar.mv.db`

Now you can restart your Hassio traccar  addon, and it traccar will re-create the databases.

**Comment by Aterfax** [comment]
I have had the DB corrupt itself again out of nowhere - something is needed to resolve this issue and remove the DB lock on start up or this plugin is basically un-usable.

**Comment by bigbigblue** [comment]
> 
> 
> I have had the DB corrupt (left itself locked somehow) itself again out of nowhere - something is needed to resolve this issue and remove the DB lock on start up or this plugin is basically un-usable.

I have had the same happen AGAIN. It is so annoying to have to re-enter the Traccar data evry time this happens. I agree with Aterfax that unless the problem can be fixed, the plugin is un-usable. I really appreciate the work put in to provide this plugin to HomeAssistant but I use Traccar as a security device and the one thing a security device needs to be is reliable.

**Comment by bigbigblue** [comment]
I have found a little more information on this error. Apparently the database used in the Traccar Plugin is Liquibase. the Locks can be released by issuing the command 'Liquibase releaseLocks' command will clear the locks - problem is that Liquibase is not a known command in the docker container.
The following SQL would work :
UPDATE DATABASECHANGELOGLOCK SET LOCKED=FALSE, LOCKGRANTED=null, LOCKEDBY=null where ID=1;   

As would dropping the DATABASECHANGELOGLOCK table (which would be automatically recreated.
Therefore it looks like a simple change to the plugin would resolve this problem. Given that only one client will ever be updating the database, locking isn't even required!

**Comment by Aterfax** [comment]
Pretty sure this will need the H2 console to achieve!

http://www.h2database.com/html/tutorial.html

**Comment by bigbigblue** [comment]
> 
> 
> Pretty sure this will need the H2 console to achieve!
>
Not a fix, but a (relatively) easy way to overcome the problem - install the MariaDB addon in HassOS and follow the instructions here [https://www.traccar.org/mysql/](https://www.traccar.org/mysql/) to tell Traccar to use MariaDB. You can then use a MySQL admin tool (such as the Chrome MYSQL admin tool) to manage the database, including dropping the lock table if Traccar gets ion a mess.
This obviously doesn't prevent the problem, but helps you to recover from it quite easily. 
I also wonder if, with MariaDB installed, the APPDaemon plugin could be used to drop the lock table each time Homeassistant starts, to prevent the problem from occurring?

**Comment by bigbigblue** [comment]
I have a working bypass for this - using MariaDB and Appdaemon plugins to HomeAssistant I am happy to share it if anyone needs it.

**Comment by frenck** [comment]
I agree, I should provide a way to hookup the add-on to MySQL.

**Comment by frenck** [comment]
Another option would be sqlite of course, which might be more portable in case of an add-on.

**Comment by frenck** [comment]
Actually, I'm not going to do this, instead, let's adjust the manual on how to configure Traccar for MySQL (Since you can do that, because the configuration XML is available for the user).

That way, the add-on still works out of the box, but a user can decide himself to which database he wants it to connect (e.g., sqlite, postgress or mysql).

**Comment by frenck** [comment]
How to use MariaDB/MySQL with this add-on has now been documented in the add-on documentation.
Also, a recommendation to use it has been added to the installation steps.
