### ISSUE TITLE
i can't not install traccar on my home assistant

### ISSUE THREAD

**Issue by boyphongsakorn** [hassio-addons/addon-traccar#50]
404 Client Error: Not Found ("no such image: hassioaddons/traccar-armv7:0.9.2: No such image: hassioaddons/traccar-armv7:0.9.2")

**Comment by frenck** [comment]
Not much I can do about that. It does exist:

![image](https://user-images.githubusercontent.com/195327/98464691-e4bf9700-21c4-11eb-97fe-10487888034c.png)


So the issue is on your end.
