### ISSUE TITLE
Presence detection on HASSIO

### ISSUE THREAD

**Issue by Job09** [hassio-addons/addon-traccar#7]
# Problem/Motivation

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by Job09** [comment]
I'd like to use Traccar with HASSIO to detect when my family components are at home.  With other device tracker (example https://www.home-assistant.io/components/device_tracker/) you can set a "devicename:" with an ID (example MAC) and detect if he's at home.
Can I do the same with Traccar? I think will be a wonderful function...
Thanks
Roberto

**Comment by Aterfax** [comment]
How to do so can be found below:

https://www.home-assistant.io/components/device_tracker.traccar/

**Comment by frenck** [comment]
As per above documentation, yes, you can.
