### ISSUE TITLE
Traccar retention

### ISSUE THREAD

**Issue by ioannispelelis** [hassio-addons/addon-traccar#83]
# Problem/Motivation
According to [Traccar documentation](https://www.traccar.org/configuration-file/) the config file is supposed to have an option for setting the database history days to keep.
This option does not seem to be possible in the traccar addon of HA.

The option should be something like below (for 30 days retention example):
`<entry key='database.historyDays'>30</entry>`
I tried putting this in the traccar.xml in the config folder. But it does not seem to take it into account since when i interrogate traccar i have gps data from end of January up to today..

Thus the mariadb database is growing (even though the purge of the recorder is set at 7 days) and i do not want to have sensitive tracking information saved for too long as it is confindential info.

## Expected behavior
To have an option to limit the size/days of gps data stored

## Actual behavior
GPS data looks to be kept indefenitely (even when we have set recorder purge at 7 days for example)

## Steps to reproduce

by checking the history of gps trackers saved it does not seem to have a limit

## Proposed changes

implement the option maybe?
`<entry key='database.historyDays'>30</entry>`
or maybe someother way to achieve this?

**Comment by frenck** [comment]
You can find the configuration file in: `/config/traccar.xml`, your are free to adjust it to your own liking.

👍

**Comment by ioannispelelis** [comment]
Hello @frenck I already tried this and put this entrykey in the config/traccar.xml to have a 30 days retention
![image](https://user-images.githubusercontent.com/57101460/114266464-cd483c80-99f6-11eb-89d9-138d811868ac.png)

But even with this i still have data since i put MariaDB in place (29/01/2021)
![image](https://user-images.githubusercontent.com/57101460/114266583-56f80a00-99f7-11eb-9632-b2567f7862de.png)

If the entrykey is supposed to work why it does not purge old data then?

**Comment by frenck** [comment]
I don't think so, but that is more a question about Traccar itself, not the add-on.
