### ISSUE TITLE
Freematics port not opening

### ISSUE THREAD

**Issue by MTrab** [hassio-addons/addon-traccar#95]
# Problem/Motivation

I added freematics to the traccar.xml, restarted add-on and the port is still not open on the host.

## Expected behavior

An port to forward traffic to

## Actual behavior

Nothing

## Steps to reproduce

Add freematics to the config and restart

## Current traccar.xml
```
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE properties SYSTEM 'http://java.sun.com/dtd/properties.dtd'>

<properties>

    <!--
    Loads default configuration for the Hass.io add-on.
    WARNING: Do not remove this line!
    -->
    <entry key='config.default'>/etc/traccar/hassio.xml</entry>

    <!--
    This is the main configuration file. All your configuration parameters should be placed in this file.
    Parameters in the main config file override values in the default file. Do not
    remove "config.default" parameter from this file unless you know what you are doing.
    For list of available parameters see following page:
        https://www.traccar.org/configuration-file/
    -->

    <!-- Enter you custom configuration below this line -->

    <entry key='freematics.port'>5170</entry>

</properties>

```

## Netstat -an |grep LISTEN on the host
![image](https://user-images.githubusercontent.com/14296463/116576891-465cf480-a910-11eb-886d-00088b35b430.png)

**Comment by sinclairpaul** [comment]
It's a UDP port, try "netstat -tulpn"

**Comment by MTrab** [comment]
Still the same 
![image](https://user-images.githubusercontent.com/14296463/116590396-fb49de00-a91d-11eb-9665-bb06b99c1646.png)

**Comment by MTrab** [comment]
Thanks - wasn't aware that it was UDP
